name: CMake

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "archlinux"]
        
    runs-on: "ubuntu-latest"
    name: ${{ matrix.os }}
        
    steps:
    - uses: actions/checkout@v2
    
    - name: Install Archlinux
      if: ${{ matrix.os == 'archlinux' }}
      run: |
        curl -L https://github.com/zaoqi/github-actions-archlinux/raw/master/install.sh | sh
        sudo pacman -S base-devel cmake

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build

    - name: Build
      # Build your program with the given configuration
      run: make -C ${{github.workspace}}/build
